### ISSUE TITLE
Installation fails "Error: Cannot find module signal-desktop/ts/textsecure"

### ISSUE THREAD

**Issue by bachrc** [witchent/matrix-puppet-signal#15]
Trying to setup the bridge on a server, but the `npm run link` seems broken :

```
root@matrix-bots:~/matrix-puppet-signal# npm run link

> matrix-puppet-signal@2.0.0 link /root/matrix-puppet-signal
> node -e "new (require('signal-client'))('matrix').link()"

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '/root/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure'
Require stack:
- /root/matrix-puppet-signal/node_modules/signal-client/index.js
- /root/matrix-puppet-signal/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at signalRequire (/root/matrix-puppet-signal/node_modules/signal-client/index.js:17:35)
    at Object.<anonymous> (/root/matrix-puppet-signal/node_modules/signal-client/index.js:88:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:6
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/matrix-puppet-signal/node_modules/signal-client/index.js',
    '/root/matrix-puppet-signal/[eval]'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! matrix-puppet-signal@2.0.0 link: `node -e "new (require('signal-client'))('matrix').link()"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the matrix-puppet-signal@2.0.0 link script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-13T10_16_57_458Z-debug.log
```

Did this happen to someone?

**Comment by witchent** [comment]
Most probably there was some error while npm installing. Try cd into node_modules/signal-desktop and run "yarn && yarn grunt", and if that does not help try to clone into a fresh directory and run npm install again.

**Comment by bachrc** [comment]
Did a fresh install, your instructions, and now this happens :

```
root@matrix-bots:~/matrix-puppet-signal# npm run link

> matrix-puppet-signal@2.0.0 link /root/matrix-puppet-signal
> node -e "new (require('signal-client'))('matrix').link()"

pre-main prep time: 2 ms
NODE_ENV production
NODE_CONFIG_DIR /root/matrix-puppet-signal/node_modules/signal-desktop/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME matrix-bots
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /root/matrix-puppet-signal/data/
config/get: Did not find user config file, cache is now empty object
config/get: Did not find ephemeral config file, cache is now empty object
key/initialize: Generating new encryption key, since we did not find it on disk
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'version' of undefined
      at new Driver (/root/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:40:70)
      at new ExecutionQueue (/root/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:532:27)
      at child.sync (/root/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:650:36)
      at child.sync (/root/matrix-puppet-signal/node_modules/backbone/backbone.js:446:28)
      at child.save (/root/matrix-puppet-signal/node_modules/backbone/backbone.js:659:22)
      at Object.put (/root/matrix-puppet-signal/node_modules/signal-client/index.js:253:10)
      at getStorageReady (/root/matrix-puppet-signal/node_modules/signal-client/index.js:1525:14)
      at startSequence (/root/matrix-puppet-signal/node_modules/signal-client/index.js:1568:3)
      at SignalClient.link (/root/matrix-puppet-signal/node_modules/signal-client/index.js:1601:12)
      at [eval]:1:42
      at Script.runInThisContext (vm.js:120:20)
      at Object.runInThisContext (vm.js:311:38)
      at Object.<anonymous> ([eval]-wrapper:10:26)
      at Module._compile (internal/modules/cjs/loader.js:1138:30)
      at evalScript (internal/process/execution.js:94:25)
      at internal/main/eval_string.js:23:3
}  reason:  TypeError: Cannot read property 'version' of undefined
    at new Driver (/root/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:40:70)
    at new ExecutionQueue (/root/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:532:27)
    at child.sync (/root/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:650:36)
    at child.sync (/root/matrix-puppet-signal/node_modules/backbone/backbone.js:446:28)
    at child.save (/root/matrix-puppet-signal/node_modules/backbone/backbone.js:659:22)
    at Object.put (/root/matrix-puppet-signal/node_modules/signal-client/index.js:253:10)
    at getStorageReady (/root/matrix-puppet-signal/node_modules/signal-client/index.js:1525:14)
    at startSequence (/root/matrix-puppet-signal/node_modules/signal-client/index.js:1568:3)
    at SignalClient.link (/root/matrix-puppet-signal/node_modules/signal-client/index.js:1601:12)
    at [eval]:1:42
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_string.js:23:3
```

**Comment by bachrc** [comment]
Ok, this worked ! Thanks for your quick answer. :) I can do a PR specifying this additional step, or do you want to do it ?

**Comment by witchent** [comment]
This is not an additional step, this is normally done by the postscript of "npm install". So something went wrong while you tried to install it. I might add that to the FAQ at one point though, let's see.
Have fun with the bridge anyway

**Comment by bachrc** [comment]
Yeah, I saw it in the install script, but I can assure you that it hasn't been done by the npm install. :/ I have Node 12 and NPM 6.

Thanks a lot for your work !

**Comment by witchent** [comment]
Yea apparently sometimes npm does not execute the post install script for some unknown reasons (never happened to me).

And you're welcome, glad to know people are using it and it is working.
