### ISSUE TITLE
What means rejected?

### ISSUE THREAD

**Issue by DoM1niC** [witchent/matrix-puppet-signal#18]
Port 8016 is here my Appservice and I connect fully local to Matrix Server over 127.0.0.1:8008
The localpart and password auth was success so far

**Config**
```
{
  "registrationPath": "signal-registration.yaml",
  "port": 8016,
  "bridge": {
    "homeserverUrl": "http://127.0.0.1:8008",
    "domain": "matrix.3dns.eu",
    "registration": "signal-registration.yaml",
    "eventStore": "data/puppet-events.db",
    "userStore": "data/puppet-users.db",
    "roomStore": "data/puppet-rooms.db"
  },
  "sendReadReceipts": true,
  "sendTypingEvents": true,
  "phoneNumber": "+49xxxxxxxxxx",
  "puppet": {
    "id": "@dom1nic:matrix.3dns.eu",
    "localpart": "dom1nic",
    "token": "KEYSTUFF"
  }
}
```
**Log**
```
INFO  2020-09-16T19:03:57.326Z Storage fetch
INFO  2020-09-16T19:03:57.344Z ConversationController: starting initial fetch
INFO  2020-09-16T19:03:57.356Z ConversationController: done with initial fetch
INFO  2020-09-16T19:03:57.357Z SignalProtocolStore: Finished caching identityKeys data
INFO  2020-09-16T19:03:57.361Z SignalProtocolStore: Finished caching sessions data
INFO  2020-09-16T19:03:57.362Z SQL channel job 4 (getItemById) succeeded in 13ms
INFO  2020-09-16T19:03:57.363Z SQL channel job 3 (getItemById) succeeded in 15ms
INFO  2020-09-16T19:03:57.367Z SignalProtocolStore: Finished caching preKeys data
INFO  2020-09-16T19:03:57.368Z SignalProtocolStore: Finished caching signedPreKeys data
triggering storage ready
INFO  2020-09-16T19:03:57.372Z Next signed key rotation scheduled for 2020-09-16T19:03:57.372Z
INFO  2020-09-16T19:03:57.374Z refreshSenderCertificate: Getting new certificate...
INFO  2020-09-16T19:03:57.381Z GET https://textsecure-service.whispersystems.org/v1/certificate/delivery?includeUuid=true
INFO  2020-09-16T19:03:57.427Z connect { firstRun: true, connectCount: 0 }
INFO  2020-09-16T19:03:57.441Z Initializing socket and listening for messages
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'split' of undefined
      at Object.unencodeNumber (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/Helpers.js:83:40)
      at new MessageReceiverInner (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/MessageReceiver.js:37:52)
      at new MessageReceiver (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/MessageReceiver.js:1363:23)
      at connect (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-client/index.js:1565:21)
      at Object.<anonymous> (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-client/index.js:1520:5)
      at triggerEvents (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/reliable_trigger.js:77:39)
      at Object.trigger (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/reliable_trigger.js:131:17)
      at getStorageReady (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-client/index.js:1744:20)
}  reason:  TypeError: Cannot read property 'split' of undefined
    at Object.unencodeNumber (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/Helpers.js:83:40)
    at new MessageReceiverInner (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/MessageReceiver.js:37:52)
    at new MessageReceiver (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/MessageReceiver.js:1363:23)
    at connect (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-client/index.js:1565:21)
    at Object.<anonymous> (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-client/index.js:1520:5)
    at triggerEvents (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/reliable_trigger.js:77:39)
    at Object.trigger (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/reliable_trigger.js:131:17)
    at getStorageReady (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-client/index.js:1744:20)
INFO  2020-09-16T19:03:57.457Z Rotating signed prekey...
ERROR 2020-09-16T19:03:57.471Z rotateSignedPrekey error: TypeError: Cannot read property 'privKey' of undefined
    at Object.generateSignedPreKey (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/libtextsecure.js:25680:31)
    at /home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/AccountManager.js:203:73
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERROR 2020-09-16T19:03:57.473Z rotateSignedPrekey() failed. Trying again in five minutes
INFO  2020-09-16T19:03:57.476Z SQL channel job 9 (getNextExpiringMessage) succeeded in 52ms
ERROR 2020-09-16T19:03:57.925Z GET https://textsecure-service.whispersystems.org/v1/certificate/delivery?includeUuid=true 401 Error
ERROR 2020-09-16T19:03:57.928Z refreshSenderCertificate: Get failed. Trying again in five minutes... HTTPError: promiseAjax: invalid response; code: 401
    at makeHTTPError (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/WebAPI.js:336:15)
    at /home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/WebAPI.js:271:36
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Original stack:
Error
    at _outerAjax (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/WebAPI.js:331:21)
    at _ajax (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/WebAPI.js:447:20)
    at Object.getSenderCertificate (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/ts/textsecure/WebAPI.js:516:20)
    at run (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/modules/refresh_sender_certificate.js:76:44)
    at runWhenOnline (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/modules/refresh_sender_certificate.js:118:7)
    at Object.initialize (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/modules/refresh_sender_certificate.js:31:3)
    at Object.<anonymous> (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-client/index.js:1512:44)
    at triggerEvents (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/reliable_trigger.js:77:39)
    at Object.trigger (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/reliable_trigger.js:131:17)
    at getStorageReady (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-client/index.js:1744:20)
INFO  2020-09-16T19:03:57.930Z Next sender certificate refresh scheduled for 2020-09-16T19:08:57.928Z
INFO  2020-09-16T19:03:57.931Z refreshOurProfile
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'getProfiles' of undefined
      at refreshOurProfile (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/modules/refresh_sender_certificate.js:20:16)
      at run (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/modules/refresh_sender_certificate.js:113:5)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}  reason:  TypeError: Cannot read property 'getProfiles' of undefined
    at refreshOurProfile (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/modules/refresh_sender_certificate.js:20:16)
    at run (/home/opt/matrix/bridges/matrix-puppet-signal/node_modules/signal-desktop/js/modules/refresh_sender_certificate.js:113:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by witchent** [comment]
As discussed in [the matrix room](https://matrix.to/#/#matrix-puppet-bridge:matrix.org), the problem was not linking the phone to the signal-desktop via npm run link as described in the readme.
