### ISSUE TITLE
When running `npm run link` a TypeError is raised in a signal-desktop component

### ISSUE THREAD

**Issue by jph** [witchent/matrix-puppet-signal#19]
Hello.

Here's my output when attempting to run `npm run link`. Sadly I just don't know enough about JS/npm/node to debug this myself.

```
npm run link

> matrix-puppet-signal@2.0.0 link /home/jph/matrix-puppet-signal
> node -e "new (require('signal-client'))('matrix').link()"

pre-main prep time: 1 ms
NODE_ENV production
NODE_CONFIG_DIR /home/jph/matrix-puppet-signal/node_modules/signal-desktop/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME PC-HOSTNAME
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/jph/matrix-puppet-signal/data/
config/get: Did not find user config file, cache is now empty object
config/get: Did not find ephemeral config file, cache is now empty object
key/initialize: Generating new encryption key, since we did not find it on disk
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'version' of undefined
      at new Driver (/home/jph/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:40:70)
      at new ExecutionQueue (/home/jph/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:532:27)
      at child.sync (/home/jph/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:650:36)
      at child.sync (/home/jph/matrix-puppet-signal/node_modules/backbone/backbone.js:446:28)
      at child.save (/home/jph/matrix-puppet-signal/node_modules/backbone/backbone.js:659:22)
      at Object.put (/home/jph/matrix-puppet-signal/node_modules/signal-client/index.js:314:10)
      at getStorageReady (/home/jph/matrix-puppet-signal/node_modules/signal-client/index.js:1704:14)
      at startSequence (/home/jph/matrix-puppet-signal/node_modules/signal-client/index.js:1753:3)
      at SignalClient.link (/home/jph/matrix-puppet-signal/node_modules/signal-client/index.js:1786:12)
      at [eval]:1:42
      at Script.runInThisContext (vm.js:132:18)
      at Object.runInThisContext (vm.js:309:38)
      at internal/process/execution.js:77:19
      at [eval]-wrapper:6:22
      at evalScript (internal/process/execution.js:76:60)
      at internal/main/eval_string.js:23:3
}  reason:  TypeError: Cannot read property 'version' of undefined
    at new Driver (/home/jph/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:40:70)
    at new ExecutionQueue (/home/jph/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:532:27)
    at child.sync (/home/jph/matrix-puppet-signal/node_modules/signal-desktop/components/indexeddb-backbonejs-adapter/backbone-indexeddb.js:650:36)
    at child.sync (/home/jph/matrix-puppet-signal/node_modules/backbone/backbone.js:446:28)
    at child.save (/home/jph/matrix-puppet-signal/node_modules/backbone/backbone.js:659:22)
    at Object.put (/home/jph/matrix-puppet-signal/node_modules/signal-client/index.js:314:10)
    at getStorageReady (/home/jph/matrix-puppet-signal/node_modules/signal-client/index.js:1704:14)
    at startSequence (/home/jph/matrix-puppet-signal/node_modules/signal-client/index.js:1753:3)
    at SignalClient.link (/home/jph/matrix-puppet-signal/node_modules/signal-client/index.js:1786:12)
    at [eval]:1:42
    at Script.runInThisContext (vm.js:132:18)
    at Object.runInThisContext (vm.js:309:38)
    at internal/process/execution.js:77:19
    at [eval]-wrapper:6:22
    at evalScript (internal/process/execution.js:76:60)
    at internal/main/eval_string.js:23:3
```

**Comment by witchent** [comment]
See the faq, just run the command again

**Comment by jph** [comment]
Right. It is clearly stated in your readme. My apologies, thank you for the quick response.
