### ISSUE TITLE
Signal Messages that are answers to other messages don't show up in matrix

### ISSUE THREAD

**Issue by FrederikP** [witchent/matrix-puppet-signal#2]
When someone replies to someone else by using the "reply" feature in signal, the message is not shown in matrix. I don't see any related errors in the log.

**Comment by witchent** [comment]
Are you talking about two other people talking to each other in a group that you're in and quoting each other?

**Comment by FrederikP** [comment]
Oh, I forgot to add that info.
In a group,

**Comment by FrederikP** [comment]
Oh and I just realized that error messages are located in the "Signal Protocol" room. I didn't see that before.

```
Error in handleThirdPartyRoomMessage TypeError: Assignment to constant variable.
    at App._handleThirdPartyRoomMessage (/matrix-puppet-signal/node_modules/matrix-puppet-bridge/src/base.js:1078:12)
    at async App.handleThirdPartyRoomMessage (/matrix-puppet-signal/node_modules/matrix-puppet-bridge/src/base.js:1038:16)
    at async App.handleSignalMessage (/matrix-puppet-signal/index.js:265:29)
    at async run (/matrix-puppet-signal/node_modules/p-queue/dist/index.js:256:29) {
  [stack]: 'TypeError: Assignment to constant variable.\n' +
    '    at App._handleThirdPartyRoomMessage (/matrix-puppet-signal/node_modules/matrix-puppet-bridge/src/base.js:1078:12)\n' +
    '    at async App.handleThirdPartyRoomMessage (/matrix-puppet-signal/node_modules/matrix-puppet-bridge/src/base.js:1038:16)\n' +
    '    at async App.handleSignalMessage (/matrix-puppet-signal/index.js:265:29)\n' +
    '    at async run (/matrix-puppet-signal/node_modules/p-queue/dist/index.js:256:29)',
  [message]: 'Assignment to constant variable.'
} {
  roomId: '[retracted]',
  senderId: '[retracted]',
  text: '"[retracted]',
  quote: {
    userId: '+49[retracted]',
    eventId: '$[retracted]',
    text: '[retracted]'
  },
  senderName: '[retracted]'
} ﻿
```

**Comment by witchent** [comment]
Oh yes sorry, that was totally my bad, I forgot something there. Should be fixed with the new matrix-puppet-bridge.
Please either reinstall or (in this case this is enough) just replace the node_modules/matrix-puppet-bridge/src/base.js with this one:
https://raw.githubusercontent.com/witchent/matrix-puppet-bridge/master/src/base.js

Thank you very much for your feedback and your log.

**Comment by FrederikP** [comment]
Can confirm it's fixed. Thanks!
